// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/todos": {
            "get": {
                "description": "Возвращает массив всех задач всех пользователей",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Получить все задачи",
                "responses": {
                    "200": {
                        "description": "Успешный ответ со списком задач",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Todo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Принимает JSON с данными задачи и создает её",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Создать задачу",
                "parameters": [
                    {
                        "description": "Данные для создания задачи",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateTodoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Задача успешно создана",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Todo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/todos/{id}": {
            "get": {
                "description": "Возвращает задачу с указанным идентификатором",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Получить задачу по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Задача найдена",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Todo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Задача не найдена",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет заголовок, описание или статус задачи по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Обновить задачу",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateTodoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Задача обновлена",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Todo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Задача не найдена",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет задачу с указанным идентификатором",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Удалить задачу",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Задача успешно удалена"
                    },
                    "400": {
                        "description": "Неверный формат ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Задача не найдена",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Возвращает массив всех зарегистрированных пользователей",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Получить всех пользователей",
                "responses": {
                    "200": {
                        "description": "Успешный ответ со списком пользователей",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.User"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Принимает JSON с email и именем, создает нового пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Создать пользователя",
                "parameters": [
                    {
                        "description": "Данные для создания пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь успешно создан",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Возвращает данные пользователя с указанным идентификатором",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Получить пользователя по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь найден",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет email или имя пользователя по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Обновить пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь обновлен",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет пользователя с указанным ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Удалить пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Пользователь успешно удален"
                    },
                    "400": {
                        "description": "Неверный ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreateTodoRequest": {
            "description": "Модель для создания новой задачи.",
            "type": "object",
            "required": [
                "title",
                "user_id"
            ],
            "properties": {
                "description": {
                    "description": "Описание задачи (не более 1000 символов)\nExample: Молоко, хлеб, яйца, масло",
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Молоко, хлеб, яйца, масло"
                },
                "done": {
                    "description": "Статус выполнения (по умолчанию false)\nExample: false",
                    "type": "boolean",
                    "example": false
                },
                "title": {
                    "description": "Заголовок задачи (обязательное поле, не более 200 символов)\nRequired: true\nExample: Купить продукты",
                    "type": "string",
                    "maxLength": 200,
                    "example": "Купить продукты"
                },
                "user_id": {
                    "description": "ID пользователя (обязательное поле)\nRequired: true\nExample: 5",
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "models.CreateUserRequest": {
            "description": "Модель для создания нового пользователя.",
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "description": "Email пользователя (обязательное поле, должен быть валидным email)\nRequired: true\nExample: user@example.com",
                    "type": "string",
                    "example": "user@example.com"
                },
                "name": {
                    "description": "Имя пользователя (обязательное поле, не более 100 символов)\nRequired: true\nExample: Иван Петров",
                    "type": "string",
                    "maxLength": 100,
                    "example": "Иван Петров"
                }
            }
        },
        "models.ErrorResponse": {
            "description": "Модель для сообщений об ошибках.",
            "type": "object",
            "properties": {
                "error": {
                    "description": "Текстовый код ошибки\nExample: invalid_request",
                    "type": "string",
                    "example": "invalid_request"
                },
                "message": {
                    "description": "Человекочитаемое сообщение об ошибке\nExample: Неверный формат запроса",
                    "type": "string",
                    "example": "Неверный формат запроса"
                }
            }
        },
        "models.SuccessResponse": {
            "description": "Стандартный успешный ответ с данными.",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Данные ответа (может быть объектом или массивом)"
                },
                "success": {
                    "description": "Статус операции (всегда true при успехе)\nExample: true",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.Todo": {
            "description": "Задача с привязкой к пользователю, заголовком, описанием и статусом.",
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Дата и время создания задачи\nExample: 2024-03-20T10:30:00Z",
                    "type": "string",
                    "example": "2024-03-20T10:30:00Z"
                },
                "description": {
                    "description": "Детальное описание задачи\nExample: Молоко, хлеб, яйца, масло",
                    "type": "string",
                    "example": "Молоко, хлеб, яйца, масло"
                },
                "done": {
                    "description": "Статус выполнения (true - выполнена, false - не выполнена)\nExample: false",
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "description": "ID уникальный идентификатор задачи\nExample: 1",
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "description": "Заголовок задачи\nExample: Купить продукты",
                    "type": "string",
                    "example": "Купить продукты"
                },
                "updated_at": {
                    "description": "Дата и время последнего обновления задачи\nExample: 2024-03-20T12:00:00Z",
                    "type": "string",
                    "example": "2024-03-20T12:00:00Z"
                },
                "user_id": {
                    "description": "ID пользователя, которому принадлежит задача\nExample: 5",
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "models.UpdateTodoRequest": {
            "description": "Модель для обновления существующей задачи.",
            "type": "object",
            "properties": {
                "description": {
                    "description": "Описание задачи (опционально, не более 1000 символов)\nExample: Новое подробное описание",
                    "type": "string",
                    "maxLength": 1000,
                    "example": "Новое подробное описание"
                },
                "done": {
                    "description": "Статус выполнения (опционально)\nExample: true",
                    "type": "boolean",
                    "example": true
                },
                "title": {
                    "description": "Заголовок задачи (опционально, не более 200 символов)\nExample: Обновленный заголовок",
                    "type": "string",
                    "maxLength": 200,
                    "example": "Обновленный заголовок"
                }
            }
        },
        "models.UpdateUserRequest": {
            "description": "Модель для обновления данных пользователя.",
            "type": "object",
            "properties": {
                "email": {
                    "description": "Email пользователя (опционально)\nExample: newemail@example.com",
                    "type": "string",
                    "example": "newemail@example.com"
                },
                "name": {
                    "description": "Имя пользователя (опционально, не более 100 символов)\nExample: Иван Сидоров",
                    "type": "string",
                    "maxLength": 100,
                    "example": "Иван Сидоров"
                }
            }
        },
        "models.User": {
            "description": "Пользователь с email, именем и временными метками.",
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Дата и время создания записи\nExample: 2024-03-20T10:30:00Z",
                    "type": "string",
                    "example": "2024-03-20T10:30:00Z"
                },
                "email": {
                    "description": "Email пользователя (уникальный)\nExample: user@example.com",
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "description": "ID уникальный идентификатор пользователя\nExample: 1",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "Имя пользователя\nExample: Иван Петров",
                    "type": "string",
                    "example": "Иван Петров"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Todo API",
	Description:      "REST API для управления пользователями и их задачами.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
